Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -3,11 +3,16 @@ on:  [workflow_dispatch, pull_request, push]
 
 jobs:
   test:
+    strategy:
+      fail-fast: true
+      matrix:
+        os:  [ubuntu]
+        version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
+    runs-on: ${{ matrix.os }}-latest
     env:
       # Used in notebooks for testing
       KAFKA_HOSTNAME: "kafka"
       KAFKA_PORT: "9092"
-    runs-on: ubuntu-latest
     defaults:
       run:
         shell: bash
@@ -31,6 +36,27 @@ jobs:
         ports:
           - 9092:9092
     steps:
-      - uses: actions/checkout@v3
-      - run: echo "PATH=$PATH:/root/.local/bin" >> $GITHUB_ENV
+      - name: Install quarto
+        run: |
+          if [ ${{ matrix.os }} == 'ubuntu' ]; then
+            wget -q https://www.quarto.org/download/latest/quarto-linux-amd64.deb
+            sudo dpkg -i quarto-linux-amd64.deb
+          else
+            wget -q https://www.quarto.org/download/latest/quarto-macos.pkg
+            sudo installer -pkg quarto-macos.pkg -target /
+          fi
       - uses: fastai/workflows/nbdev-ci@master
+        with:
+          version: ${{ matrix.version }}
+      - name: test build docs
+        run: |
+          test -f setup.py && pip install -e ".[dev]"
+          nbdev_mkdocs docs
+          if [ -f "mkdocs/site/index.html" ]; then
+            echo "docs built successfully."
+          else
+            echo "index page not found in rendered docs."
+            ls -la
+            ls -la mkdocs/site/
+            exit 1
+          fi
